version: '3'

services:
  app:
    build: .
    image: auth-ad-app
    command: >
      bash -c "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env
    ports:
      - 8000:8000